### ISSUE TITLE
[BUG] Empty authority reputations on start

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#262]
**Describe the bug**

When starting the standalone node with non development keys, the ` DKG::authority_reputations` is empty. This causes a panic in `worker.rs` when it attempts to `set_up_rounds`. More specifically, we only set authority reputations within the function call `set_up_rounds` yet call `worker.get_authority_reputations(header)` to pass in `reputations: &HashMap<AuthorityId, i64>` as a param. See below sequence of steps that describes the problem. 

1. [`set_up_rounds`](https://github.com/webb-tools/dkg-substrate/blob/master/dkg-gadget/src/persistence.rs#L209) is called in `try_resume_dkg`
2. [ `get_authority_reputations`](https://github.com/webb-tools/dkg-substrate/blob/master/dkg-gadget/src/persistence.rs#L217) is called to pass in `reputations` as a param to `set_up_rounds`
3. [`get_reputations`](https://github.com/webb-tools/dkg-substrate/blob/master/runtime/src/lib.rs#L676) is called, and panics trying to iterate over an empty `DKG::authority_reputations`

**To Reproduce**
1. `cargo build --release -p dkg-standalone-node`
2. Insert `acco`, `gran`, `aura`, `wdkg` keys x3 nodes using [`key insert`](https://docs.substrate.io/tutorials/v3/private-network/#add-keys-to-the-keystore) command
```
# example key insert command for grandpa key for local chain
key insert --base-path /tmp/tiger \
--chain=local \
--scheme Ed25519 \
--suri "..." \
--password-interactive \
--key-type gran
```

3. Open 3 terminals and start x3 nodes that are not pre-determined accounts (Alice, Bob, Charlie, etc.) 
```
# example start command; note this is for local setup (e.g. chain=local)
dkg-standalone-node \
  --base-path /tmp/tiger \
  --name tiger \
  --chain=local \
  --port 30333 \
  --ws-port 9944 \
  --validator 
```
4. Error will begin once blocks are being finalized

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]: 2022-03-21 23:02:24 Failed to get next signed proposal: Unable to get next proposal batch
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]: ====================
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]: Version: 3.0.0-fd2385f-x86_64-linux-gnu
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:    0: sp_panic_handler::set::{{closure}}
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:    1: std::panicking::rust_panic_with_hook
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:              at rustc/a77da2d454e6caa227a85b16410b95f93495e7e0/library/std/src/panicking.rs:610:17
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:    2: std::panicking::begin_panic_handler::{{closure}}
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:              at rustc/a77da2d454e6caa227a85b16410b95f93495e7e0/library/std/src/panicking.rs:502:13
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:              at rustc/a77da2d454e6caa227a85b16410b95f93495e7e0/library/std/src/sys_common/backtrace.rs:139:18
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:    4: rust_begin_unwind
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:              at rustc/a77da2d454e6caa227a85b16410b95f93495e7e0/library/std/src/panicking.rs:498:5
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:    5: core::panicking::panic_fmt
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:              at rustc/a77da2d454e6caa227a85b16410b95f93495e7e0/library/core/src/panicking.rs:107:14
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:    6: core::result::unwrap_failed
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:              at rustc/a77da2d454e6caa227a85b16410b95f93495e7e0/library/core/src/result.rs:1613:5
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:    7: dkg_gadget::worker::DKGWorker<B,C,BE>::get_authority_reputations
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:    8: dkg_gadget::persistence::try_resume_dkg
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:    9: dkg_gadget::worker::DKGWorker<B,C,BE>::process_block_notification
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   10: dkg_gadget::worker::DKGWorker<B,C,BE>::handle_import_notifications
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   12: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   13: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   14: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   16: std::thread::local::LocalKey<T>::with
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   17: tokio::park::thread::CachedParkThread::block_on
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   18: tokio::runtime::handle::Handle::block_on
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   19: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   20: tokio::runtime::task::harness::Harness<T,S>::poll
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   21: tokio::runtime::blocking::pool::Inner::run
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   22: std::sys_common::backtrace::__rust_begin_short_backtrace
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   23: core::ops::function::FnOnce::call_once{{vtable.shim}}
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   24: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:              at rustc/a77da2d454e6caa227a85b16410b95f93495e7e0/library/alloc/src/boxed.rs:1694:9
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:              at rustc/a77da2d454e6caa227a85b16410b95f93495e7e0/library/alloc/src/boxed.rs:1694:9
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:       std::sys::unix::thread::Thread::new::thread_start
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:              at rustc/a77da2d454e6caa227a85b16410b95f93495e7e0/library/std/src/sys/unix/thread.rs:106:17
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   25: start_thread
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]:   26: clone
Mar 21 23:02:24 dkg-standalone-1 dkg-standalone-node[58507]: Thread 'tokio-runtime-worker' panicked at 'get reputations is always available: Application(Execution(Other("Exported method DKGApi_get_reputations is not found")))', /home/dkg-tiger/dkg/dkg-substrate/dkg-gadget/src/worker.rs:289
  ```
</details> 

**Expected behaviour**

There should be a default case or an `Option` passed back in [`get_reputations`](https://github.com/webb-tools/dkg-substrate/blob/master/runtime/src/lib.rs#L676)  or `get_authority_reputations` that does not cause a panic when iterating over authority reputations. 

**Environment (please complete the following information):**
 - OS: MacOs
 - Rust version(e.g. `rustc --version`): `nightly-2021-11-20-aarch64-apple-darwin`
 - Branch/commit: `master`

**Comment by dutterbutter** [comment]
I got a very similar error again, however this time instead of `Exported method DKGApi_get_reputations is not found` it was, 
```
Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Application(Execution(Other("Exported method DKGApi_keygen_threshold is not found")))', webb/dkg-substrate/dkg-gadget/src/worker.rs:275
```

 Can anyone else reproduce this error? Or is it something I am doing on start up. 
 
 @drewstone can you try to reproduce?
