### ISSUE TITLE
[BUG] run-standalone.sh crashes

### ISSUE THREAD

**Issue by Nutomic** [webb-tools/dkg-substrate#562]
**Describe the bug**

The run-standalone script crashes after running a few seconds. This seems to be the main error message: 
```
Thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/felix/workspace/webb/dkg-substrate/dkg-gadget/src/async_protocols/blockchain_interface.rs:125
```

**To Reproduce**
1. Clone and setup repo
2. Run `./scripts/run-standalone.sh`
3. See error

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```
Version: 3.0.0-a78528d40f2

0: sp_panic_handler::set::{{closure}}
1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/alloc/src/boxed.rs:2002:9
std::panicking::rust_panic_with_hook
at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:692:13
2: std::panicking::begin_panic_handler::{{closure}}
at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:577:13
3: std::sys_common::backtrace::__rust_end_short_backtrace
at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/sys_common/backtrace.rs:137:18
4: rust_begin_unwind
at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:575:5
5: core::panicking::panic_fmt
at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/panicking.rs:64:14
6: core::panicking::panic
at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/panicking.rs:114:5
7: dkg_gadget::async_protocols::blockchain_interface::_::<impl dkg_gadget::async_protocols::blockchain_interface::BlockchainInterface for alloc::sync::Arc<T>>::gossip_public_key
8: dkg_gadget
::====================
async_protocols
::Version: keygen::3.0.0-736308f0b2cstate_machine
::
<impl dkg_gadget :: async_protocols ::0state_machine: ::StateMachineHandlersp_panic_handler<::BIset>:: {for{ closuremulti_party_ecdsa}::}protocols
:: multi_party_ecdsa :: gg_20201::: state_machine<::allockeygen::::boxedKeygen::>Box::<on_finishF::,{A{>closure }as}
core::ops :: function ::9Fn: <<Argscore>::>pin::::callPin
<             at P>/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/alloc/src/boxed.rs :as2002 :core9::
future      ::stdfuture::::panickingFuture::>rust_panic_with_hook::
poll             at
/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs : 69210:: 13dkg_gadget
::async_protocols :: new_inner ::2{: {stdclosure::}panicking}::
begin_panic_handler :: 11{: {<closurefutures_util}::}future::
future             at ::map/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs:::Map577<:Fut13,
F >   as3 : corestd::::futuresys_common::::futurebacktrace::::Future__rust_end_short_backtrace>
::             at poll/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/sys_common/backtrace.rs
:137 : 1812
: < futures_util :: future4::: futurerust_begin_unwind::
flatten             at ::Flatten/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs<Fut:,575<:Fut5
as  core :: future5:::
futurecore====================
::::
FuturepanickingVersion: >::::3.0.0-a78528d40f2panic_fmtOutput

>             at
/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/panicking.rsas: 64 core: ::14 future
0:: : future :: sp_panic_handlerFuture::6>: set::core::poll::{
panicking{ ::closure panic}13
}:              at </rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/panicking.rs
tokio :::114future :::5poll_fn
::1PollFn : < <F alloc>7 ::: asboxeddkg_gadget ::::coreasync_protocolsBox::::<futureblockchain_interfaceF::::future,_::::AFuture<>>impl :: aspolldkg_gadget
::core async_protocols:: ::ops14blockchain_interface::: ::functiondkg_gadgetBlockchainInterface:::: Fnasync_protocolsfor<:: keygenArgsalloc::>::handlersync::>::<::Arcimplcall<
Tdkg_gadget             at >::/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/alloc/src/boxed.rs>async_protocols:::::2002gossip_public_keyGenericAsyncHandler:
<9 Out
>       >8::std: setup_keygen::dkg_gadget::panicking::{::async_protocols{rust_panic_with_hook::closure
}keygen             at }::/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs
state_machine: ::692 <:15impl13:
dkg_gadgetdkg_gadget ::::worker async_protocols:: ::DKGWorker2state_machine<: ::BstdStateMachineHandler,<BE::BI,panicking>C:: ,begin_panic_handlerforGE:: {>multi_party_ecdsa{::::closurespawn_keygen_protocolprotocols}::::}{multi_party_ecdsa
{::             at closuregg_2020}/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs::}:
577state_machine ::: keygen16::13: Keygen
tokio>:: ::loomon_finish ::::std {::3{unsafe_cell: closure::std}UnsafeCell::}<sys_common
T:: >backtrace :: ::with_mut9__rust_end_short_backtrace
:
<             at  core/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/sys_common/backtrace.rs17:::: pin137tokio:::::Pin18runtime<
::P task>::  core as:: Core4core<::: Tfuturerust_begin_unwind,::
Sfuture             at >::/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/panicking.rs::Futurepoll:>
575:: poll:
518 :
tokio10:: : runtime dkg_gadget:: ::task5async_protocols::::: harnessnew_inner::core::Harness{::<{Tpanickingclosure,}::S}panic_fmt>

::              at poll /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/panicking.rs
11: : 64 <:19futures_util14: ::
tokiofuture :::: runtimefuture:: ::scheduler6map::: ::multi_threadcoreMap::::<workerFutpanicking::,::ContextFpanic::>
run_task              at
as/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/core/src/panicking.rs  :core 114::20:future: 5::tokio
future:: ::runtimeFuture ::> scheduler::::7pollmulti_thread:
::dkg_gadgetworker :::: Contextasync_protocols12::::: runblockchain_interface<
::futures_util :: _future21::::: <futuretokioimpl:::: flattenmacrosdkg_gadget::::::Flattenscoped_tlsasync_protocols<::Fut::ScopedKey,blockchain_interface<<::TFutBlockchainInterface>  ::asforset
corealloc :::: futuresync22::: future::tokio::Arc::Future<runtime>T::::>schedulerOutput>::>::multi_thread gossip_public_key::as
worker ::core run::
future  :: 8future23: ::: dkg_gadgetFuturetokio::>::async_protocols::loom::poll::keygen
std:::: state_machineunsafe_cell ::::13UnsafeCell<: <impl<T tokio>dkg_gadget::::::futurewith_mutasync_protocols::
::poll_fn ::state_machine PollFn::24<StateMachineHandler: F<tokio>BI::> runtime as::for taskcore ::::coremulti_party_ecdsafuture::::::Coreprotocolsfuture<::::TFuturemulti_party_ecdsa,>::S::>gg_2020poll::::
pollstate_machine
::  14keygen : ::25dkg_gadgetKeygen: ::>tokioasync_protocols::::::runtimeon_finishkeygen::::::taskhandler{::::{harness<closure::impl}Harness }<dkg_gadget
T:: ,async_protocols S:: >GenericAsyncHandler9::<: pollOut<
>core >:: ::pin26setup_keygen::: ::tokio{Pin::{<runtimeclosureP::}>blocking}:: pool
as ::  Innercore15::: run::dkg_gadget
::future worker:: ::future27DKGWorker::: <stdFutureB::>sys_common,::::BEpollbacktrace,
::C __rust_begin_short_backtrace,
GE 10> : ::28dkg_gadgetspawn_keygen_protocol: ::::core{async_protocols::{::opsclosurenew_inner::}::function}::{
FnOnce{ ::closure call_once}16{}: {
tokiovtable ::. loomshim::11}std}: ::
<unsafe_cell futures_util:: ::UnsafeCell29future<: T<::>allocfuture::::::with_mutboxedmap
::::Box Map< <F17,Fut: Atokio>,:: Fruntimeas>::  taskcoreas:::: coreopscore::::Corefunction<::::TfutureFnOnce,::<SfutureArgs>>::::>Futurepoll::>
call_once::
poll             at 18
: /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/alloc/src/boxed.rstokio :::1988 runtime:::129task:
::<      harnessfutures_util<::alloc::Harness::future<boxed::T::future,BoxS<::>Fflatten::,::pollAFlatten
><  Futas , <19coreFut: :: tokioops::as::runtime function::core::scheduler::FnOnce::future<multi_thread::Args::future>worker>::::::ContextFuturecall_once::>
run_task::             at
Output/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/alloc/src/boxed.rs >:  198820as::  9tokio
core::      ::runtimestdfuture::::scheduler::sys::future::multi_thread::unix::Future::workerthread>::::::ContextThreadpoll::::
runnew
::  thread_start13
21:              at : <tokio/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/sys/unix/thread.rstokio:::::macros108future:::::scoped_tls17poll_fn::
ScopedKey:: <PollFn T<30>F: ::><unknown>set

as     core3122::: : <unknown>futuretokio
::::
futureruntime
::::Thread 'Futureschedulertokio-runtime-worker>::' panicked at '::multi_threadcalled `Option::unwrap()` on a `None` valuepoll::',
worker/home/felix/workspace/webb/dkg-substrate/dkg-gadget/src/async_protocols/blockchain_interface.rs:: :run 125
14

This is a bug. Please report it at:

:  support.anonymous.andkg_gadget23

::: async_protocolstokio::::keygenloom::::handlerstd::::<unsafe_cellimpl:: UnsafeCelldkg_gadget<::Tasync_protocols>::::GenericAsyncHandlerwith_mut<
Out > >24::: setup_keygentokio::::{runtime{::closuretask}::}core
::Core < T15,: Sdkg_gadget>::::workerpoll::
DKGWorker < B25,: BEtokio,::Cruntime,::GEtask>::::harnessspawn_keygen_protocol::::Harness{<{Tclosure,}S}>
:: poll
16 :  tokio26::: loomtokio::::stdruntime::::unsafe_cellblocking::::UnsafeCellpool<::TInner>::::runwith_mut

2717: : stdtokio::::sys_commonruntime::::backtracetask::::__rust_begin_short_backtracecore
:: Core <28T: ,coreS::>ops::::pollfunction
:: FnOnce ::18call_once: {tokio{::vtableruntime.::shimtask}::}harness
:: Harness <29T: ,<S>::poll
19: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
20: tokio::runtime::scheduler::multi_thread::worker::Context::run
alloc::boxed  21: ::tokioBox::<macrosF::,scoped_tlsA::>ScopedKey <asT >core::::setops
:: function ::22FnOnce: <tokioArgs::>runtime>::::schedulercall_once::
multi_thread             at ::/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/alloc/src/boxed.rsworker:::1988run:
9
23<: alloctokio::::boxedloom::::Boxstd<::Funsafe_cell,::AUnsafeCell>< Tas> ::corewith_mut::
ops :: function24::: FnOncetokio<::Argsruntime>::>task::::call_oncecore
::             at Core/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/alloc/src/boxed.rs<:T1988,:S9>
::poll
std :: sys25::: unixtokio::::threadruntime::::Threadtask::::newharness::::thread_startHarness
<             at T/rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/sys/unix/thread.rs,:S108>:::17poll

3026: : <unknown>tokio
:: runtime ::31blocking: ::<unknown>pool
::
Inner
::Thread 'runtokio-runtime-worker
' panicked at ' called `Option::unwrap()` on a `None` value ', 27/home/felix/workspace/webb/dkg-substrate/dkg-gadget/src/async_protocols/blockchain_interface.rs: :std125::
sys_common
This is a bug. Please report it at:

::support.anonymous.anbacktrace

::__rust_begin_short_backtrace
28: core::ops::function::FnOnce::call_once{{vtable.shim}}
29: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/alloc/src/boxed.rs:1988:9
<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/alloc/src/boxed.rs:1988:9
std::sys::unix::thread::Thread::new::thread_start
at /rustc/c18a5e8a5b1afb0d7a582fe9ebad4c1996c90da3/library/std/src/sys/unix/thread.rs:108:17
30: <unknown>
31: <unknown>


Thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /home/felix/workspace/webb/dkg-substrate/dkg-gadget/src/async_protocols/blockchain_interface.rs:125

This is a bug. Please report it at:

support.anonymous.an

  ```
</details> 

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Manjaro Linux
 - Rust version(e.g. `rustc --version`): rustc 1.69.0-nightly (c18a5e8a5 2023-01-25)
 - Branch/commit: master (736308f0b2c5f57623402ce87c392c7a95eff88b)

**Other information and links**

**Comment by tbraun96** [comment]
Line 125 of `blockchain_interface`:

`let bundle = self.test_bundle.as_ref().unwrap();`

Note: This code only executes if the feature `testing` is enabled. Was the DKG standalone build with the feature "testing" enabled?

**Comment by Nutomic** [comment]
No I didnt enable that feature at all. Im just executing the standalone script which runs these commands:

https://github.com/webb-tools/dkg-substrate/blob/master/scripts/run-standalone.sh#L34

**Comment by tbraun96** [comment]
Strange. We see here the code only executes if testing enabled:

<img width="667" alt="Screenshot 2023-04-12 at 9 04 19 AM" src="https://user-images.githubusercontent.com/38082993/231466639-3fade129-237c-4c7b-8c73-cabf5c954173.png">

And by default, the `dkg-standalone-node` does not enable the `testing` feature:
<img width="547" alt="Screenshot 2023-04-12 at 9 05 44 AM" src="https://user-images.githubusercontent.com/38082993/231466928-58af42aa-a11b-49be-8bdc-4178478c0784.png">

**Comment by tbraun96** [comment]
The quick patch here is to replace the unwraps with `if-let` statements. But, it's still strange that `testing` is somehow being enabled? Are there any additional cargo flags in your environment?

**Comment by Nutomic** [comment]
No, I also tried a clean build with the standalone script and its the same crash. I also cant tell why the feature is getting enabled.
